name: "Check for package updates"
on:
  workflow_dispatch:
  schedule:
    - cron: "26 6 * * *" # https://crontab.guru/#26_10_*_*_*
     
jobs:
  update-flake-packages:
    strategy:
      fail-fast: false
      matrix:
        nixPath:
          - nixpkgs=channel:nixos-24.05
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@V28
        with:
          nix_path: "${{ matrix.nixPath }}"
          extra_nix_config: |
            experimental-features = nix-command flakes
    
      - uses: DeterminateSystems/magic-nix-cache-action@main
    
      - name: Show nixpkgs version
        run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'

      - name: configure git bot
        run: |
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
  
      - name: Run nix-update on each package
        run: nix-shell -p nix-update --run 'sh update-packages.sh'
        
      - name: Run git log to show changes
        run: git log -10
